import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import { inrShort } from "./storage";
import type { Dream, Debt, OtherGoal, Profile } from "./api";

const GOLD: [number, number, number] = [201, 162, 39];
const DARK: [number, number, number] = [20, 22, 38];
const MUTED: [number, number, number] = [120, 120, 130];

function header(doc: jsPDF, title: string, subtitle?: string) {
  doc.setFillColor(...DARK);
  doc.rect(0, 0, 210, 28, "F");
  doc.setTextColor(...GOLD);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("NSI Vision Board", 14, 13);
  doc.setFontSize(11);
  doc.setTextColor(220, 220, 220);
  doc.text(title, 14, 22);
  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(180, 180, 180);
    doc.text(subtitle, 196, 22, { align: "right" });
  }
}

function footerEach(doc: jsPDF) {
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(`Page ${i} of ${pages}`, 196, 290, { align: "right" });
    doc.text("Generated by NSI Vision Board", 14, 290);
  }
}

export function exportFullReport(opts: {
  profile: Profile | null | undefined;
  dreams: Dream[];
  debts: Debt[];
  goals: OtherGoal[];
}) {
  const { profile, dreams, debts, goals } = opts;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const today = new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });

  // ===== Cover =====
  header(doc, "Personal Wealth & Dreams Report", today);
  let y = 42;
  doc.setTextColor(40, 40, 50);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(profile?.full_name || profile?.nickname || "Dreamer", 14, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  if (profile?.city) doc.text(profile.city, 14, y), (y += 5);
  if (profile?.motivation) {
    doc.setFont("helvetica", "italic");
    doc.text(`"${profile.motivation}"`, 14, y, { maxWidth: 180 });
    y += 8;
  }

  // Profile table
  const profileRows: [string, string][] = [
    ["Age", profile?.age ? String(profile.age) : "—"],
    ["Monthly Income", inrShort(Number(profile?.monthly_income ?? 0))],
    ["Current Savings", inrShort(Number(profile?.savings ?? 0))],
    ["Retirement Age", profile?.retirement_age ? String(profile.retirement_age) : "—"],
  ];
  autoTable(doc, {
    startY: y + 4,
    head: [["Profile", "Value"]],
    body: profileRows,
    theme: "grid",
    headStyles: { fillColor: GOLD, textColor: 20 },
    styles: { fontSize: 10 },
  });

  // ===== Summary =====
  const dreamTotal = dreams.reduce((a, b) => a + (b.amount || 0), 0);
  const dreamSaved = dreams.reduce((a, b) => a + (b.saved || 0), 0);
  const achievedDreams = dreams.filter((d) => (d.saved || 0) >= (d.amount || 0) && d.amount > 0);
  const activeDreams = dreams.filter((d) => (d.saved || 0) < (d.amount || 0) || d.amount <= 0);
  const debtTotal = debts.reduce((a, b) => a + (b.amount || 0), 0);
  const emiTotal = debts.reduce((a, b) => a + (b.emi || 0), 0);
  const goalTotal = goals.reduce((a, b) => a + (b.amount || 0), 0);

  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 8,
    head: [["Summary", "Amount"]],
    body: [
      ["Total Dream Goal", inrShort(dreamTotal)],
      ["Total Saved Toward Dreams", inrShort(dreamSaved)],
      ["Dreams Achieved", `${achievedDreams.length} of ${dreams.length}`],
      ["Total Debt", inrShort(debtTotal)],
      ["Monthly EMI Outflow", inrShort(emiTotal)],
      ["Other Goals", inrShort(goalTotal)],
      ["Net Required to Reach All Dreams", inrShort(Math.max(dreamTotal - dreamSaved, 0))],
    ],
    theme: "grid",
    headStyles: { fillColor: GOLD, textColor: 20 },
    styles: { fontSize: 10 },
  });

  // ===== Active Dreams =====
  doc.addPage();
  header(doc, "Active Dreams", today);
  autoTable(doc, {
    startY: 36,
    head: [["#", "Dream", "Category", "Target", "Saved", "Remaining", "Progress", "Years"]],
    body: activeDreams.map((d, i) => {
      const remain = Math.max((d.amount || 0) - (d.saved || 0), 0);
      const pct = d.amount > 0 ? ((d.saved || 0) / d.amount) * 100 : 0;
      return [
        String(i + 1),
        `${d.emoji ?? ""} ${d.name}`,
        d.category,
        inrShort(d.amount),
        inrShort(d.saved),
        inrShort(remain),
        `${pct.toFixed(0)}%`,
        String(d.deadline_years ?? "—"),
      ];
    }),
    theme: "striped",
    headStyles: { fillColor: GOLD, textColor: 20 },
    styles: { fontSize: 9 },
  });

  // ===== Achieved Dreams =====
  if (achievedDreams.length) {
    doc.addPage();
    header(doc, "Achieved Dreams 🏆", today);
    autoTable(doc, {
      startY: 36,
      head: [["#", "Dream", "Amount", "Started", "Achieved", "Days Taken"]],
      body: achievedDreams.map((d, i) => {
        const start = d.created_at ? new Date(d.created_at) : null;
        const end = d.updated_at ? new Date(d.updated_at) : null;
        const days = start && end ? Math.max(1, Math.round((+end - +start) / 86400000)) : null;
        return [
          String(i + 1),
          `${d.emoji ?? ""} ${d.name}`,
          inrShort(d.amount),
          start?.toLocaleDateString("en-IN") ?? "—",
          end?.toLocaleDateString("en-IN") ?? "—",
          days != null ? `${days} days` : "—",
        ];
      }),
      theme: "striped",
      headStyles: { fillColor: GOLD, textColor: 20 },
      styles: { fontSize: 9 },
    });
    autoTable(doc, {
      startY: (doc as any).lastAutoTable.finalY + 6,
      body: [["Total Achieved Value", inrShort(achievedDreams.reduce((a, b) => a + (b.amount || 0), 0))]],
      theme: "grid",
      styles: { fontSize: 11, fontStyle: "bold" },
    });
  }

  // ===== Debts =====
  doc.addPage();
  header(doc, "Debts", today);
  autoTable(doc, {
    startY: 36,
    head: [["#", "Name", "Type", "Amount", "EMI", "Interest %", "Stress"]],
    body: debts.map((d, i) => [
      String(i + 1),
      d.name,
      d.type,
      inrShort(d.amount),
      inrShort(d.emi),
      `${d.interest}%`,
      `${d.stress}/5`,
    ]),
    theme: "striped",
    headStyles: { fillColor: GOLD, textColor: 20 },
    styles: { fontSize: 9 },
  });
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 6,
    body: [
      ["Total Debt", inrShort(debtTotal)],
      ["Monthly EMI", inrShort(emiTotal)],
    ],
    theme: "grid",
    styles: { fontSize: 11, fontStyle: "bold" },
  });

  // ===== Other Goals =====
  if (goals.length) {
    doc.addPage();
    header(doc, "Other Goals", today);
    autoTable(doc, {
      startY: 36,
      head: [["#", "Title", "Category", "Amount", "Priority"]],
      body: goals.map((g, i) => [
        String(i + 1),
        g.title,
        g.category,
        inrShort(g.amount),
        String(g.priority),
      ]),
      theme: "striped",
      headStyles: { fillColor: GOLD, textColor: 20 },
      styles: { fontSize: 9 },
    });
  }

  footerEach(doc);
  doc.save(`NSI-Report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
