/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlannerRouteImport } from './routes/planner'
import { Route as MotivationRouteImport } from './routes/motivation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadershipRouteImport } from './routes/leadership'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as DreamsRouteImport } from './routes/dreams'
import { Route as DebtsRouteImport } from './routes/debts'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const PlannerRoute = PlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => rootRouteImport,
} as any)
const MotivationRoute = MotivationRouteImport.update({
  id: '/motivation',
  path: '/motivation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadershipRoute = LeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamsRoute = DreamsRouteImport.update({
  id: '/dreams',
  path: '/dreams',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsRoute = DebtsRouteImport.update({
  id: '/debts',
  path: '/debts',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/debts': typeof DebtsRoute
  '/dreams': typeof DreamsRoute
  '/history': typeof HistoryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/motivation': typeof MotivationRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/debts': typeof DebtsRoute
  '/dreams': typeof DreamsRoute
  '/history': typeof HistoryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/motivation': typeof MotivationRoute
  '/planner': typeof PlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/achievements': typeof AchievementsRoute
  '/dashboard': typeof DashboardRoute
  '/debts': typeof DebtsRoute
  '/dreams': typeof DreamsRoute
  '/history': typeof HistoryRoute
  '/leadership': typeof LeadershipRoute
  '/login': typeof LoginRoute
  '/motivation': typeof MotivationRoute
  '/planner': typeof PlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/achievements'
    | '/dashboard'
    | '/debts'
    | '/dreams'
    | '/history'
    | '/leadership'
    | '/login'
    | '/motivation'
    | '/planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/achievements'
    | '/dashboard'
    | '/debts'
    | '/dreams'
    | '/history'
    | '/leadership'
    | '/login'
    | '/motivation'
    | '/planner'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/achievements'
    | '/dashboard'
    | '/debts'
    | '/dreams'
    | '/history'
    | '/leadership'
    | '/login'
    | '/motivation'
    | '/planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AchievementsRoute: typeof AchievementsRoute
  DashboardRoute: typeof DashboardRoute
  DebtsRoute: typeof DebtsRoute
  DreamsRoute: typeof DreamsRoute
  HistoryRoute: typeof HistoryRoute
  LeadershipRoute: typeof LeadershipRoute
  LoginRoute: typeof LoginRoute
  MotivationRoute: typeof MotivationRoute
  PlannerRoute: typeof PlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planner': {
      id: '/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof PlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motivation': {
      id: '/motivation'
      path: '/motivation'
      fullPath: '/motivation'
      preLoaderRoute: typeof MotivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leadership': {
      id: '/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof LeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreams': {
      id: '/dreams'
      path: '/dreams'
      fullPath: '/dreams'
      preLoaderRoute: typeof DreamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts': {
      id: '/debts'
      path: '/debts'
      fullPath: '/debts'
      preLoaderRoute: typeof DebtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AchievementsRoute: AchievementsRoute,
  DashboardRoute: DashboardRoute,
  DebtsRoute: DebtsRoute,
  DreamsRoute: DreamsRoute,
  HistoryRoute: HistoryRoute,
  LeadershipRoute: LeadershipRoute,
  LoginRoute: LoginRoute,
  MotivationRoute: MotivationRoute,
  PlannerRoute: PlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
